
CREATE TABLE GRAPH_METRIX(GRAPH_ID INT,CONN_MATRIX VARCHAR(1000));

CREATE TABLE VERTICES(
	VERTEX_ID INT NOT NULL CONSTRAINT VERTES_PK PRIMARY KEY,
	LABEL VARCHAR(20),
	SHAPE VARCHAR(20),
	COLOR VARCHAR(10)
);

create table GRAPH(
GRAPH_ID INT GENERATED ALWAYS AS IDENTITY CONSTRAINT GRAPH_ID_PK PRIMARY KEY,
VERTICES INT,
BI_DIRECTIONAL INT,
CONSTRAINT VERTEX_FK FOREIGN KEY (VERTICES) REFERENCES VERTICES(VERTEX_ID) 
);





--Cleaner
DROP TABLE GRAPH_METRIX;
DROP TABLE GRAPH;
